[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Netlify Functions設定
[functions]
  directory = "netlify/functions"

# リダイレクト設定（SPA用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200